blog/urls.py
from django.urls import path
from .views import render_posts,post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post

# Create your views here.
def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html',{
        'posts': posts
    })

def post_detail(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html',{
        'post': post
    })

portfolio/views.py
from django.shortcuts import render
from portfolio.models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {
        'projects': projects
    })

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

    <h1>POST</h1>

    <h3>{{post.title}}</h3>
    <p>{{post.date}}</p>
    <img src="{{post.image.url}}" alt="" width="100">
    <p>{{post.content}}</p>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

    <h1>POSTS</h1>

    {% for post in posts %}
        <h3>{{post.title}}</h3>
        <p>{{post.date|date:'M d Y'|upper}}</p>
        <p>{{post.content|truncatechars:250}}</p>
        <img src="{{post.image.url}}" alt="" width="100">
        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
    {% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

    <header class="row bg-black">
        <div class="col md-4 my-auto">
            <img src="{% static 'portfolio/profile.jpg' %}" alt="" width="300">
        </div>
        <div class="col-md-8 my-auto">
            <h1>Hola soy <strong>Tomas</strong></h1>
            <h3>Desarrollador Python</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse alias consectetur voluptas, quo, minus laudantium sequi consequatur reprehenderit cumque expedita commodi atque aliquid neque. Expedita numquam similique, enim tempora laboriosam vitae natus ut quia optio magnam aliquam odit tempore eligendi nemo laudantium. Sequi sed hic placeat praesentium esse qui amet non enim incidunt reprehenderit laboriosam tenetur repudiandae dolorem in quis officia maxime accusantium doloribus voluptatem doloremque, optio corporis ab? Quia totam quaerat, sint est veniam neque molestias rerum nisi esse? Libero alias quaerat error quasi, quia cumque dolore animi quod porro architecto veritatis amet quae laboriosam sunt pariatur magnam quidem?</p>
            <a href="{% static 'portfolio/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Descargar CV</a>
        </div>
    </header>

    <div class="row my-4 text-center">

        <h3>Mis proyectos</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, incidunt.</p>

        {% for project in projects %}
            <div class="col-md-4 pd-4">
                <div class="card bg-black card-project">
                    <img src="{{project.image.url}}" alt="" class="card-img-top">
                    <div class="card-body">
                        <h2>{{project.title}}</h2>
                        <p>{{project.description}}</p>
                        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">TD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Descargar CV</a>
        </li>
      </ul>
    </div>
  </div>
</nav>